const rank={"A2.1":1,"A2.2":2,"B1.1":3,"B1.2":4};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const sha256=async s=>{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')};
function pa2(x){x=Number(x);return Number.isFinite(x)?x>=6.5?'B1.1':x>=4.75?'A2.2':'A2.1':null}
function pa3(x){x=Number(x);return Number.isFinite(x)?x>=83?'B1.1':x>=63?'A2.2':'A2.1':null}
async function user(req,env){const t=(req.headers.get('cookie')||'').match(/xldv_session=([^;]+)/)?.[1];if(!t)return null;const r=await env.XLDV_DB.prepare('select s.token,s.expires_at,u.* from sessions s join users u on u.id=s.user_id where s.token=? and s.expires_at>? and u.active=1').bind(t,Date.now()).first();return r||null}
async function audit(env,u,action,entity='',id='',meta={}){if(!u)return;await env.XLDV_DB.prepare('insert into audit_log(actor_username,role,school,action,entity,entity_id,metadata) values(?,?,?,?,?,?,?)').bind(u.username,u.role,u.school||null,action,entity,id,JSON.stringify(meta)).run()}
function scope(u, q=[]){if(u.role==='CSGD')q.push(['school',u.school]);return q}
function matchRows(rows,u,p){return rows.filter(r=>u.role!=='CSGD'||r.school===u.school).filter(r=>!p.school||r.school===p.school).filter(r=>!p.cohort||r.cohort===p.cohort).filter(r=>!p.major||r.major===p.major).filter(r=>!p.level||r.best_level===p.level).filter(r=>!p.method||r.method===p.method).filter(r=>!p.alert||JSON.parse(r.alerts||'[]').length).filter(r=>!p.search||[r.mssv,r.full_name,r.major].some(x=>String(x||'').toLowerCase().includes(p.search.toLowerCase())))}
function issues(r){const a=[];if(!r.full_name)a.push('Thiếu họ tên');if(!r.school)a.push('Thiếu CSGDĐHTV');if(r.registration_pa1 && !r.pa1_level)a.push('Đăng ký PA1 nhưng chưa có kết quả/chứng chỉ PA1 được xác minh');if(r.pa2_score===null||r.pa2_score===undefined||r.pa2_score==='')a.push('Chưa có điểm THPT English 2026');if((r.pa2_score===null||r.pa2_score===undefined||r.pa2_score==='') && (r.pa3_score===null||r.pa3_score===undefined||r.pa3_score===''))a.push('Chưa có dữ liệu PA2/PA3 để xác định mức');if(JSON.parse(r.alerts||'[]').length)a.push(...JSON.parse(r.alerts||'[]'));return [...new Set(a)]}
function decorate(r){const is=issues(r);const unresolved=r.processing_status!=='DONE';return {...r,auto_issues:is,needs_action:unresolved && is.length>0,processing_status:r.processing_status||'OPEN',processed_by:r.processed_by||'',processed_at:r.processed_at||'',resolution_note:r.resolution_note||''}}
export async function onRequest(context){const {request,env}=context;const url=new URL(request.url);const path=url.pathname.replace(/^\/api\/?/,'');
 try{
  if(request.method==='POST'&&path==='login'){const {username,password}=await request.json();const u=await env.XLDV_DB.prepare('select * from users where username=? and active=1').bind(username||'').first();if(!u||u.password_hash!==(await sha256(password||'')))return json({error:'Sai tài khoản hoặc mật khẩu'},401);const token=crypto.randomUUID()+crypto.randomUUID();await env.XLDV_DB.prepare('insert into sessions(token,user_id,expires_at) values(?,?,?)').bind(token,u.id,Date.now()+8*3600*1000).run();await audit(env,u,'LOGIN','user',String(u.id));return new Response(JSON.stringify({user:{username:u.username,role:u.role,school:u.school}}),{headers:{'content-type':'application/json','set-cookie':`xldv_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800`}})}
  const u=await user(request,env); if(!u)return json({error:'Chưa đăng nhập'},401);
  if(path==='logout'&&request.method==='POST'){await audit(env,u,'LOGOUT','user',String(u.id));return new Response('',{status:204,headers:{'set-cookie':'xldv_session=; Path=/; Max-Age=0'}})}
  if(path==='me')return json({username:u.username,role:u.role,school:u.school});
  if(path==='dashboard'){const p=Object.fromEntries(url.searchParams);let rows=await env.XLDV_DB.prepare('select * from students order by school,mssv limit 5000').all();rows=matchRows(rows.results,u,p).map(decorate);const levels={};const methods={};const pa3Levels={'B1.1':0,'A2.2':0,'A2.1':0,'Chưa có kết quả':0};const pa3Bands={'83–100':0,'63–82':0,'<63':0,'Chưa có điểm':0};let alerts=0;for(const r of rows){const l=r.best_level||'Chưa xác định';levels[l]=(levels[l]||0)+1;const m=r.method||'Chưa xác định';methods[m]=(methods[m]||0)+1;if(r.pa3_level)pa3Levels[r.pa3_level]=(pa3Levels[r.pa3_level]||0)+1;else pa3Levels['Chưa có kết quả']++;const sc=Number(r.pa3_score);if(Number.isFinite(sc)){if(sc>=83)pa3Bands['83–100']++;else if(sc>=63)pa3Bands['63–82']++;else pa3Bands['<63']++;}else pa3Bands['Chưa có điểm']++;if(JSON.parse(r.alerts||'[]').length)alerts++}const schools={};for(const r of rows){const k=r.school||'Chưa xác định';schools[k] ||= {school:k,total:0,determined:0,pa3:0,alerts:0,needsAction:0};schools[k].total++;if(r.best_level)schools[k].determined++;if(r.pa3_score!==null&&r.pa3_score!==undefined)schools[k].pa3++;if(JSON.parse(r.alerts||'[]').length)schools[k].alerts++;if(r.needs_action)schools[k].needsAction++;}await audit(env,u,'VIEW_DASHBOARD','dashboard','summary');return json({kpi:{total:rows.length,determined:rows.filter(r=>r.best_level).length,missing:rows.filter(r=>!r.best_level).length,alerts,needsAction:rows.filter(r=>r.needs_action).length,pa3Result:rows.filter(r=>r.pa3_level).length},levels:Object.entries(levels).map(([label,value])=>({label,value})),methods:Object.entries(methods).map(([label,value])=>({label,value})),pa3Levels:Object.entries(pa3Levels).map(([label,value])=>({label,value})),pa3Bands:Object.entries(pa3Bands).map(([label,value])=>({label,value})),schools:Object.values(schools).map(x=>({...x,progress:x.total?Math.round(x.determined/x.total*100):0})),needs:rows.filter(r=>r.needs_action).slice(0,50).map(r=>({mssv:r.mssv,full_name:r.full_name,school:r.school,issues:r.auto_issues,level:r.best_level||'Chưa xác định'})),serverTime:new Date().toISOString(),reportRule:'CSĐT báo cáo kết quả về ĐHĐN trong vòng 05 ngày sau khi có kết quả kiểm tra xếp lớp.'})}
  if(path==='students'){const p=Object.fromEntries(url.searchParams);let rows=await env.XLDV_DB.prepare('select * from students order by school,mssv limit 5000').all();rows=matchRows(rows.results,u,p).map(decorate);await audit(env,u,'VIEW_STUDENTS','student','list',{count:rows.length});return json(rows)}
  if(path==='needs'){const p=Object.fromEntries(url.searchParams);let rows=await env.XLDV_DB.prepare('select * from students order by school,mssv limit 5000').all();rows=matchRows(rows.results,u,p).map(decorate).filter(r=>r.auto_issues.length>0);if(p.type)rows=rows.filter(r=>r.auto_issues.includes(p.type));if(p.status&&p.status!=='ALL')rows=rows.filter(r=>(r.processing_status||'OPEN')===p.status);await audit(env,u,'VIEW_NEEDS_ACTION','student','needs',{count:rows.length});return json(rows)}
  if(path==='resolve'&&request.method==='POST'){if(u.role!=='ADMIN')return json({error:'Chỉ ĐHNN được xử lý hồ sơ'},403);const body=await request.json();const mssv=String(body.mssv||'').trim();if(!mssv)return json({error:'Thiếu MSSV'},400);const r=await env.XLDV_DB.prepare('select * from students where mssv=?').bind(mssv).first();if(!r)return json({error:'Không tìm thấy MSSV'},404);const status=body.status==='OPEN'?'OPEN':'DONE';const note=String(body.note||'').trim();const now=new Date().toISOString();await env.XLDV_DB.prepare('update students set processing_status=?,processed_by=?,processed_at=?,resolution_note=?,status=case when ?=? then ? else status end,updated_at=CURRENT_TIMESTAMP where mssv=?').bind(status,status==='DONE'?u.username:null,status==='DONE'?now:null,note,status,'DONE','Đã xử lý',mssv).run();await audit(env,u,status==='DONE'?'RESOLVE_NEEDS_ACTION':'REOPEN_NEEDS_ACTION','student',mssv,{note});return json({ok:true,mssv,status,processed_by:status==='DONE'?u.username:null,processed_at:status==='DONE'?now:null,resolution_note:note})}

  if(path==='audit'){if(!['ADMIN','BGH'].includes(u.role))return json({error:'Không có quyền'},403);const rows=await env.XLDV_DB.prepare('select * from audit_log order by id desc limit 1000').all();return json(rows.results)}
  if(path==='import'&&request.method==='POST'){if(u.role!=='ADMIN')return json({error:'Chỉ ĐHNN được cập nhật Dashboard'},403);const body=await request.json();if(!Array.isArray(body.rows))return json({error:'rows phải là mảng'},400);const seen=new Set(),dups=new Set();const stmt=env.XLDV_DB.prepare('insert into students(mssv,full_name,school,cohort,major,pa2_score,pa2_level,pa3_score,pa3_level,best_level,method,status,alerts,registration_pa1,registration_pa3,note,pa3_source) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(mssv) do update set full_name=excluded.full_name,school=excluded.school,cohort=excluded.cohort,major=excluded.major,pa2_score=excluded.pa2_score,pa2_level=excluded.pa2_level,pa3_score=excluded.pa3_score,pa3_level=excluded.pa3_level,best_level=excluded.best_level,method=excluded.method,status=excluded.status,alerts=excluded.alerts,registration_pa1=excluded.registration_pa1,registration_pa3=excluded.registration_pa3,note=excluded.note,pa3_source=excluded.pa3_source,processing_status='OPEN',processed_by=NULL,processed_at=NULL,resolution_note='',updated_at=CURRENT_TIMESTAMP');const batch=[];for(const r of body.rows){if(!r.mssv)continue;const mssv=String(r.mssv).trim();if(seen.has(mssv))dups.add(mssv);seen.add(mssv);const a=[];const l2=pa2(r.pa2_score);const l3=pa3(r.pa3_score);const ms=[l2&&{m:'PA2',l:l2,s:r.pa2_score},l3&&{m:'PA3',l:l3,s:r.pa3_score}].filter(Boolean).sort((a,b)=>(rank[b.l]||0)-(rank[a.l]||0));if(new Set(ms.map(x=>x.l)).size>1)a.push('Kết quả các phương án khác mức');const best=ms[0];if(r.registration_pa1&&!r.pa1_level)a.push('Đăng ký PA1 nhưng chưa có kết quả/chứng chỉ PA1 được xác minh');if(!l2&&!l3)a.push('Chưa có dữ liệu PA2/PA3 để xác định mức');batch.push(stmt.bind(mssv,r.full_name||'',r.school||'',r.cohort||'',r.major||'',Number.isFinite(Number(r.pa2_score))?Number(r.pa2_score):null,l2,Number.isFinite(Number(r.pa3_score))?Number(r.pa3_score):null,l3,best?.l||null,best?.m||null,best?'Đã xác định':'Chưa xác định',JSON.stringify([...new Set(a)]),r.registration_pa1||'',r.registration_pa3||'',r.note||'',r.pa3_source||'PA3'));}if(batch.length)await env.XLDV_DB.batch(batch);await audit(env,u,'IMPORT_EXCEL','student','bulk',{rows:batch.length,mode:'upsert',duplicates:[...dups]});return json({ok:true,rows:batch.length,duplicates:[...dups],auto:true})}
  return json({error:'Not found'},404)
 }catch(e){return json({error:e.message||String(e)},500)}
}
